### ISSUE TITLE
[Question] about wasm size

### ISSUE THREAD

**Issue by katopz** [Menci/vite-plugin-wasm#12]
In rust project after build I got `web3_wasm.wasm` = `1.2MB`
But after `run-s clean && vite` (yarn dev) to trigger the plugin  tocopy `wasm` to `node_modules`.
I got `web3_wasm_bg.wasm` = `706KB` 😳 (which is good in case nothing break)

So the question is what (or who) make the size smaller?
I try to peek a around the code but didn't see anything related to compression.

Thanks.

**Comment by Menci** [comment]
This plugin have nothing to do with the WASM file itself. I don't know.
