### ISSUE TITLE
Firefox web workers

### ISSUE THREAD

**Issue by segevfiner** [Menci/vite-plugin-wasm#18]
AFAIK Firefox doesn't support ESM in workers ATM so setting `workers.format` to `es` will break the resulting sure in Firefox. I think Vite explicitly has code to transform workers in dev mode rather than rely on ESM so they will work in Firefox. Any way to get this plugin to work with classic workers?

**Comment by Menci** [comment]
Rollup only accepts code with TLA in ES mode, [not in IIFE mode](https://github.com/rollup/rollup/issues/3623). So I'm going to add some magic hack in my plugin (vite-plugin-top-level-await) to make the worker code build as ES first and then transform the built code to IIFE to make it work in Firefox.

**Comment by segevfiner** [comment]
BTW, Firefox is going to add

**Comment by Menci** [comment]
Supported with [vite-plugin-top-level-await](https://github.com/Menci/vite-plugin-top-level-await) `v1.3.0`.
