### ISSUE TITLE
using wasm with Nuxt3

### ISSUE THREAD

**Issue by cesarecaoduro** [Menci/vite-plugin-wasm#19]
I am trying to use a wasm with Nuxt3 but it keeps failing...anyone that can help me with configuration?

nuxt.config.ts
```
import wasm from 'vite-plugin-wasm';

export default defineNuxtConfig({
    vite: {
        plugins: [
            wasm()
        ]
    }
})
```

**Comment by Menci** [comment]
Any reproduce?

**Comment by cesarecaoduro** [comment]
Hi @Menci, here you go...
https://github.com/cesarecaoduro/nuxt-occ

**Comment by Menci** [comment]
Found a sample for you to use it with Vite. Note that you don't need this plugin.

https://github.com/donalffons/opencascade.js/pull/141/files#diff-881623410b5b8961b0a239ca26372de6ac76895634a7331256117145896fa250R52
