### ISSUE TITLE
Wrong export signature (`default`) 

### ISSUE THREAD

**Issue by schickling** [Menci/vite-plugin-wasm#2]
Given you're using a `default` export in your `index.ts` in combination with `"module": "CommonJS",` in your `tsconfig.json` there are currently "two levels" of default exports.

My current workaround: 

![CleanShot 2022-05-26 at 17 35 37](https://user-images.githubusercontent.com/1567498/170522297-5c2b3386-9c32-4f79-9da8-974a095f83f8.png)

**Comment by Menci** [comment]
Fixed in https://github.com/Menci/vite-plugin-wasm/commit/567eaa06c458e802ab6afd4048786927fa0723aa.
