### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by xzxzhixin** [Menci/vite-plugin-wasm#20]
![image](https://user-images.githubusercontent.com/43931152/206662882-8e43f798-be3c-4151-a552-5072cf894734.png)
![image](https://user-images.githubusercontent.com/43931152/206662906-669a1893-8a00-4547-a481-11cf6543bd7b.png)
![image](https://user-images.githubusercontent.com/43931152/206663046-68b24ab2-f41e-49ab-9236-9fb3bfa0f50d.png)
报错Uncaught (in promise) SyntaxError: Unexpected reserved word
![image](https://user-images.githubusercontent.com/43931152/206662979-dc9fbf0b-d9ea-49d9-b424-3acfe73f38a3.png)
在webpack5中是正常的，使用的rust构建命令是：**wasm-pack build --target bundler**

**Comment by katopz** [comment]
I think to use `import` there it should be `<script type="module">`.

**Comment by Menci** [comment]
reproduce project pls

**Comment by xzxzhixin** [comment]
https://gitee.com/zhi_xin_qiantong/vue2-learning

**Comment by xzxzhixin** [comment]
https://gitee.com/zhi_xin_qiantong/vue2-learning
我的项目地址
![image](https://user-images.githubusercontent.com/43931152/206839367-d9dd8443-d5fc-4660-856b-05d7f97a449c.png)
![image](https://user-images.githubusercontent.com/43931152/206839386-fe55127c-2354-467a-8011-2fed4c3e5cb4.png)

**Comment by xzxzhixin** [comment]
> I think to use `import` there it should be `<script type="module">`.

这个没有用，还是一样的错误

**Comment by Menci** [comment]
I failed to build your project (`pnpm install`, `pnpm build`).

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/11341955/206888311-c9fcc2b8-4893-4f8a-abee-c93e5d48ec79.png">

**Comment by Menci** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/11341955/206888438-8a254eb8-acd1-4c44-9534-b0c93b2cd008.png">

Can't reproduce it.

**Comment by xzxzhixin** [comment]
> <img alt="image" width="1470" src="https://user-images.githubusercontent.com/11341955/206888438-8a254eb8-acd1-4c44-9534-b0c93b2cd008.png">
> 
> Can't reproduce it.

在低版本谷歌内核中有问题，这个低版本谷歌内核是360浏览器
![image](https://user-images.githubusercontent.com/43931152/206955253-56aac0f2-f106-4b04-9089-853c24fac25a.png)
高版本中谷歌就没有这个问题，这个高版本是谷歌浏览器
![image](https://user-images.githubusercontent.com/43931152/206955266-5a69cd82-5722-444e-8723-4a67f9e9af85.png)

**Comment by Menci** [comment]
I reviewed your screenshot and realized that it's in dev mode.

![image](https://user-images.githubusercontent.com/11341955/206999601-5b45d55b-5500-4842-9133-d9a9dd2c60d7.png)

You shouldn't use a non-latest browser for dev mode. Vite doesn't support legacy / outdated browsers in dev mode. Even if you want your app to support outdated / legacy browsers, you should dev in latest browsers and test the built bundle in your target browsers.

Please test if the built bundle (with `yarn vite build`) works in your outdated browser.
