### ISSUE TITLE
wasm-pack module import is undefined

### ISSUE THREAD

**Issue by voxelstack** [Menci/vite-plugin-wasm#21]
I had a NextJS project setup where I would build a rust library with `wasm-pack`, install it with `file:wasm-bindgen-module`, set `asyncWebAssembly` on the Webpack config and then import and use it like this:
```
import { f } from "wasm-bindgen-module";
f();
```

I am now moving over to SvelteKit and the "(aka. Webpack's asyncWebAssembly)" led me to believe I would be able to do the same but when I do `onMount(() => f())`, I get `Cannot read properties of undefined (reading 'f')`.

Here's my `vite.config.js`:
```
const config = {
	plugins: [sveltekit(), wasm(), topLevelAwait()],
	optimizeDeps: {
		exclude: ["wasm-bindgen-module"],
	},
};
```

Am I missing anything?

**Comment by voxelstack** [comment]
Doing some further testing, it seems like the plugins are not being used. I would still appreciate help since I can't find anything about using vite plugins on SvelteKit with `vitePreprocess` but at least for now it's not an issue with `vite-plugin-wasm`.

**Comment by Antonio-Bennett** [comment]
Also experiencing this with Sveltekit

**Comment by Menci** [comment]
any reproduce project?

**Comment by Menci** [comment]
Please test it with the latest version of the plugin. See #23.

**Comment by Menci** [comment]
Closing since no response.

**Comment by Antonio-Bennett** [comment]
@Menci I gave up lol came back to it still getting this error. 
![image](https://user-images.githubusercontent.com/31296212/222842113-58ca8daf-dd1d-4116-ba07-9484a6c2f85a.png)
![image](https://user-images.githubusercontent.com/31296212/222842171-52567aac-a675-4717-be5f-3acf0896fc0d.png)

**Comment by SKTT1Ryze** [comment]
Also meet this issue, is there a solution now?

**Comment by Menci** [comment]
Sorry I'll take a look on this

**Comment by Menci** [comment]
Just checked your repo @Antonio-Bennett. It's the same as https://github.com/Menci/vite-plugin-wasm/issues/27, which is a bug of wasm-pack https://github.com/rustwasm/wasm-bindgen/commit/721c86c3467750bf2a46bf85941e6c211ae9e87a, not this plugin.

See https://github.com/rustwasm/wasm-pack/issues/1235 for the issue and https://github.com/rustwasm/wasm-pack/pull/1237 for a fix.

**Comment by Menci** [comment]
@SKTT1Ryze @voxelstack Please also check you projects. If there're different issues in your project, send to me to investigate.

**Comment by Sytten** [comment]
In the meantime you can disable manually treeshaking for the module:
```typescript
export default defineConfig({
  plugins: [wasm(), topLevelAwait()],
  build: {
    rollupOptions: {
      plugins: [
        {
          name: "disable-treeshake",
          transform(code, id) {
            if (id.includes("MYMODULE")) {
              return { moduleSideEffects: "no-treeshake" };
            }
          },
        },
      ],
    },
  },
});
```

**Comment by SKTT1Ryze** [comment]
@Menci Solved in my case, i just didn't load the`*_bg.wasm` file with `init` function.

**Comment by SKTT1Ryze** [comment]
> @Menci Solved in my case, i just didn't load the`*_bg.wasm` file with `init` function.

My project: https://github.com/DarkNeos/neos-ts
