### ISSUE TITLE
how wait for async load to complete

### ISSUE THREAD

**Issue by BLaZeKiLL** [Menci/vite-plugin-wasm#27]
I am not sure if this is the correct place to open this issue but I am trying to load a local wasm node module in my app, It works fine in the dev build but when I do a prod build imports from wasm are undefined. as a workaround I had to add

```js
await import('game-of-life');
```

before I call any of my wasm functions. I also have a top-level import for the types

```js
import { Universe, Cell } from 'game-of-life';
import { memory } from 'game-of-life/game_of_life_bg.wasm';
```

I understand async loading of wasm is a bit new, so I am unsure if I am doing this correctly. It just doesn't feel correct 2 have import statements to the same module

complete source code can be found [here](https://github.com/BLaZeKiLL/game-of-life/blob/master/www/apps/app-game-of-life/src/app/app.element.ts)

**Comment by Menci** [comment]
Let me check

**Comment by Menci** [comment]
I found that the direct reason that make it undefined is the assignment to `wasm` variable is missing in the generated bundle. And it works with Rollup's tree-shaking disabled.

```diff
diff --git a/www/apps/app-game-of-life/src/app/app.element.ts b/www/apps/app-game-of-life/src/app/app.element.ts
index 1fa599a..34a8235 100644
--- a/www/apps/app-game-of-life/src/app/app.element.ts
+++ b/www/apps/app-game-of-life/src/app/app.element.ts
@@ -18,7 +18,7 @@ export class AppElement extends HTMLElement {
   private height = 128;

   async connectedCallback() {
-    await import('game-of-life'); // wait for wasm module to load, should be better way
+    // await import('game-of-life'); // wait for wasm module to load, should be better way

     this.innerHTML = `<canvas id="${this.ID}"></canvas>`;

diff --git a/www/apps/app-game-of-life/vite.config.ts b/www/apps/app-game-of-life/vite.config.ts
index 5624b7a..6a5cf10 100644
--- a/www/apps/app-game-of-life/vite.config.ts
+++ b/www/apps/app-game-of-life/vite.config.ts
@@ -7,7 +7,10 @@ export default defineConfig({
   cacheDir: '../../node_modules/.vite/app-game-of-life',

   build: {
-    target: 'esnext'
+    target: 'esnext',
+    rollupOptions: {
+      treeshake: false
+    }
   },

   optimizeDeps: {
```

It doesn't seem to be an issue with this plugin but seems to be Vite/Rollup's. I'll try to produce it and submit an issue to Vite or Rollup. If so, let's keep this issue open for reference before it's fixed.

**Comment by Menci** [comment]
No, I think it's an issue with wasm-pack. It generates the `pacakge.json` with `sideEffects: false` and use a `__wbg_set_wasm` statement to set the wasm module object. I think it's the exptected behavior for it to be tree-shaked...

**Comment by Menci** [comment]
I think the bug is introduced in https://github.com/rustwasm/wasm-bindgen/commit/721c86c3467750bf2a46bf85941e6c211ae9e87a. Let me submit a bug to rustwasm.

**Comment by Menci** [comment]
https://github.com/rustwasm/wasm-pack/issues/1235

**Comment by BLaZeKiLL** [comment]
Thanks for looking into it and providing the explanation, it makes sense I'll track the issue on waan-bindgen maybe try a fix

**Comment by BLaZeKiLL** [comment]
yeah adding to side-effects fixes it
