### ISSUE TITLE
Add option to bundle .wasm file instead of inlining wasm binary as base64

### ISSUE THREAD

**Issue by hamza1311** [Menci/vite-plugin-wasm#35]
There should be an option to bundle the WASM as `.wasm` file. At the moment, WASM is encoded as base64 and included in JS. This has several disadvantages, including but not limited to slower execution.

Please allow externalizing wasm files

**Comment by Menci** [comment]
How do you find it's encoded?. The WASM file is bundled.

**Comment by hamza1311** [comment]
Apologies, I should've mentioned this in the issue. I'm using library mode to build a library that exposes an API from the WASM file. The contents of the wasm file are encoded inside the final JS file

**Comment by Yongle-Fu** [comment]
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="env" error: module is not an object or function
--------------------
my import files is xxx.js and xxx.wasm build from cpp project by emcc

**Comment by Menci** [comment]
@Yongle-Fu Please try Webpack's `asyncWebAssembly`. Does that works?

**Comment by Yongle-Fu** [comment]
webpack works

**Comment by Yongle-Fu** [comment]
// code works
  addWasmInit().then((instance) => {
      console.log(instance);
      console.log(instance.exports.add(1, 2));
  });

  // code not works, Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="env" error: module is not an object or function
  loadWasmInit().then((instance) => {
      console.log(instance);
  });

  // code not works, another error
  const liboz = await loadWasm();

**Comment by Menci** [comment]
`?init` is not related to this plugin, closing.
