### ISSUE TITLE
default import is undefined (bun)

### ISSUE THREAD

**Issue by eye-wave** [Menci/vite-plugin-wasm#39]
wasm is undefined when using bun v1.0.0

command used:
$ bun run "$(bun pm bin)/vite" dev
> failed to load config from .../my-project/vite.config.ts
error when starting dev server:
TypeError: wasm is not a function. (In 'wasm()', 'wasm' is undefined)
    at module code (.../my-project/vite.config.ts.timestamp-....mjs:7:11)
    at processTicksAndRejections (:1:1302)
error: script "dev" exited with code 1 (SIGHUP)
---

config file
```ts
// vite.config.ts
import { defineConfig } from "vite"
import { sveltekit } from "@sveltejs/kit/vite"
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [sveltekit(),wasm()],
})
```

---
standalone bun example
```js
import * as wasm from "vite-plugin-wasm"

console.log(wasm)
// results:

// Bun:
// Module {
//   default: undefined
// }

// Node:
// [Module: null prototype] { default: [Function: wasm] }
//

```

**Comment by zavx0z** [comment]
https://github.com/oven-sh/bun/issues/7146

**Comment by Menci** [comment]
See also my comments in https://github.com/oven-sh/bun/issues/7146#issuecomment-1848883257.
