### ISSUE TITLE
wasm-bindgen memory optimization seems to have broken the plugin

### ISSUE THREAD

**Issue by Secretmapper** [Menci/vite-plugin-wasm#5]
Steps to reproduce:

1. Do the wasm-pack [tutorial](https://rustwasm.github.io/docs/wasm-pack/)
2. Install Vite with this plugin
3. Get error: Cannot access `memory` before initialization on the `bg` file. (Truncated below):

```js
import * as wasm from '/-/hello-wasm/hello_wasm_bg.wasm?import';

let cachedUint8Memory0;
function getUint8Memory0() {
    if (cachedUint8Memory0.byteLength === 0) {
        cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachedUint8Memory0;
}

cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer); // Uncaught ReferenceError: Cannot access 'memory' before initialization
```

The memory checking seems to have been changed since this PR: https://github.com/rustwasm/wasm-bindgen/pull/2886 and I'm guessing the initialization logic is different from what's now needed since the wasm file is referenced in the top level.

**Comment by Menci** [comment]
Could you please test this WASM binding with [Webpack5's `asyncWebAssembly`](https://webpack.js.org/configuration/experiments/) and check if Webpack 5 could handle this correctly?

**Comment by Secretmapper** [comment]
@Menci I've tried to look into it, and in the process it seems like I should have checked the related issues of the one I linked - the bug seems to have been fixed by this PR:

https://github.com/rustwasm/wasm-bindgen/pull/2965

Closing as it's a wasm-bindgen issue.

**Comment by litaiquan** [comment]
> Could you please test this WASM binding with [Webpack5's `asyncWebAssembly`](https://webpack.js.org/configuration/experiments/) and check if Webpack 5 could handle this correctly?

I tested that everything was normal in webpack5

**Comment by Menci** [comment]
Yes, I also found that Webpack 5 could load buggy bindings successfully. But Node.js's native ESM WASM loader fails.
