### ISSUE TITLE
Plugin fails to load a WASM file create with GOLANG

### ISSUE THREAD

**Issue by ethastings** [Menci/vite-plugin-wasm#51]
When attempting to load a WASM that was written in Golang and compiled using GOARCH=wasm GOOS=js go build -o mian.wasm the resulting vite app does not load and has this error in the web browser console: 
Uncaught SyntaxError: missing '}' after module specifier list [main.wasm:6:17]

**Comment by Menci** [comment]
Could you please attach the WASM file?
