### ISSUE TITLE
Error: Could not resolve "a"

### ISSUE THREAD

**Issue by rongaza** [Menci/vite-plugin-wasm#53]
I'm getting the following error.

[Here is a sandbox of the project.](https://codesandbox.io/p/devbox/crazy-goldstine-pjgqws?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clryzf39h00073b6akmzp1121%2522%252C%2522sizes%2522%253A%255B53.766816143497756%252C46.233183856502244%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clryzf39g00023b6a0q6u8vsg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clryzf39g00043b6at8k8bj94%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clryzf39h00063b6anosb2bgk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B68.03120938860947%252C31.96879061139053%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clryzf39g00023b6a0q6u8vsg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clryzf39g00013b6axnfbgz6s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clryzf39g00023b6a0q6u8vsg%2522%252C%2522activeTabId%2522%253A%2522clryzf39g00013b6axnfbgz6s%2522%257D%252C%2522clryzf39h00063b6anosb2bgk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clryzf39h00053b6aq6m7y114%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clryzf39h00063b6anosb2bgk%2522%252C%2522activeTabId%2522%253A%2522clryzf39h00053b6aq6m7y114%2522%257D%252C%2522clryzf39g00043b6at8k8bj94%2522%253A%257B%2522id%2522%253A%2522clryzf39g00043b6at8k8bj94%2522%252C%2522activeTabId%2522%253A%2522clryzf39g00033b6a445ok3uz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clryzf39g00033b6a445ok3uz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clryzrmbq01553b6ai65aeaxu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clryzrmez00kyegipg1by57rq%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

<img width="1069" alt="Screenshot 2024-01-29 at 9 34 41 AM" src="https://github.com/Menci/vite-plugin-wasm/assets/3395698/8a3cdc5c-f521-4fc8-8d20-e4467adcef49">

**Comment by thecannabisapp** [comment]
@rongaza how did you fix this error?

**Comment by rawasaditya** [comment]
I want to know fix for this
