### ISSUE TITLE
Cannot read properties of undefined (reading 'load') 

### ISSUE THREAD

**Issue by wanglei8381** [Menci/vite-plugin-wasm#6]
originalWasmPlugin = resolvedConfig.plugins.find(plugin => plugin.name === "vite:wasm");

vite:wasm这个插件找不到导致的（vite 3.0）

**Comment by Menci** [comment]
Vite 3.0 的确不需要这部分代码了，我有空适配一下

**Comment by Menci** [comment]
不对，还是要这段代码的，我提的 `fileToUrl` 在 3.0 还没有 landing，我适配一下 3.0 的新内置 WASM 插件名

**Comment by Menci** [comment]
Sorry. The code was ready 3 days ago but I forgot to publish it ...
